name: scylla
root: .

windows:
  - sensors_and_odom:
      layout: tiled 
      synchronize: off
      panes:
        - lidar:
            - echo "Starting Lidar..."
            - ./build/bin/lidar_node
        - imu:
            - echo "Starting IMU..."
            - ./build/bin/imu_mag_node
        - flow:
            - echo "Starting Optical Flow..."
            - ./build/bin/flow_node
  - control:
      layout: tiled 
      synchronize: off
      panes:
        - control:
            - echo "Starting Control..."
            - ./build/bin/control_node
