"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class ScanPoint(object):

    __slots__ = ["x", "y"]

    __typenames__ = ["float", "float"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.x = 0.0
        """ LCM Type: float """
        self.y = 0.0
        """ LCM Type: float """

    def encode(self):
        buf = BytesIO()
        buf.write(ScanPoint._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ff", self.x, self.y))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ScanPoint._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ScanPoint._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = ScanPoint()
        self.x, self.y = struct.unpack(">ff", buf.read(8))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if ScanPoint in parents: return 0
        tmphash = (0x7c2d87baacd686e3) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if ScanPoint._packed_fingerprint is None:
            ScanPoint._packed_fingerprint = struct.pack(">Q", ScanPoint._get_hash_recursive([]))
        return ScanPoint._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", ScanPoint._get_packed_fingerprint())[0]

